import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './(components)/Navbar'
import Footer from './(components)/Footer'
const inter = Inter({ subsets: ['latin'] })
import { Providers } from "@/redux/provider";
export const metadata = {
  title: 'Hour Tracker',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Providers>
        <body className={`${inter.className} bg-light text-dark`}>
          <Navbar />
          <div className='min-h-[90vh]'>
            {children}
          </div>
          <Footer />
          <div id="portal" />
        </body>
      </Providers>
    </html>
  )
}
